### PR TITLE
feat: add docs qa bot

### PR DESCRIPTION
**Pull request by shazhou2015**
add docqa to docs website

### CODE REVIEW

**Comment by samuelcolvin** [comment]
What is this doing?

**Comment by shazhou2015** [comment]
> What is this doing?

It's a chatbot based on Jina AI tech stack, could answer all the questions that the docs could answer.

**Comment by samuelcolvin** [comment]
Thanks, would have been useful to put that in the title or description.

I've tried searching a few times for answer which are held in the "Types" section of the docs (this is auto generated from docstrings), your tool doesn't seem to ever provide answers from that section of  the docs. Is that content somehow not indexed?

That's a problem since >90% of docs for this package are in that section.

**Comment by shazhou2015** [comment]
> I've tried searching a few times for answer which are held in the "Types" section of the docs (this is auto generated from docstrings), your tool doesn't seem to ever provide answers from that section of the docs. Is that content somehow not indexed?
> 
> That's a problem since >90% of docs for this package are in that section.
Thanks  for your feedback, we will look into this issue.

**Pull request closed without merging**
