### PR TITLE
Patch pprint to make pytest diffs nicer for big objects

### PR DESCRIPTION
**Pull request by alexmojaki**
Replaces https://github.com/alexmojaki/dirty-equals/pull/1

Closes https://github.com/samuelcolvin/dirty-equals/issues/73

### CODE REVIEW

**Comment by alexmojaki** [comment]
ready to review

**Comment by samuelcolvin** [comment]
LGTM, please can you add an screenshot or similar example to PR showing how this improves the display?

**Comment by alexmojaki** [comment]
As in the original issue, before:

```
E       AssertionError: assert (['ddsdsdads ', 'sfafsdsd', 'dfds sdfsef', 'sfdssdf ', 'sdsadfs', 'dsfsdfsd', 'cfdfdfd', 'dgffgfdgfd', 'fdsfsdgfsdgsf'], 1, 2, 3, 4, 5, 6, 7, 8, 9) == (['ddsdsdads ', 'sfafsdsd', 'dfds sdfsef', 'sfdssdf ', 'sdsadfs', 'dsfsdfsd', 'cfdfdfd', 'dgffgfdgfd', 'fdsfsdgfsdgsf'], 1, 2, 3, 4, 5, 6, 7, 8, 0)
E         At index 9 diff: 9 != 0
E         Full diff:
E           (
E         -  ['ddsdsdads ', 'sfafsdsd', 'dfds sdfsef', 'sfdssdf ', 'sdsadfs', 'dsfsdfsd', 'cfdfdfd', 'dgffgfdgfd', 'fdsfsdgfsdgsf'],
E         +  ['ddsdsdads ',
E         +   'sfafsdsd',
E         +   'dfds sdfsef',
E         +   'sfdssdf ',
E         +   'sdsadfs',
E         +   'dsfsdfsd',
E         +   'cfdfdfd',
E         +   'dgffgfdgfd',
E         +   'fdsfsdgfsdgsf'],
E            1,
E            2,
E            3,
E            4,
E            5,
E            6,
E            7,
E            8,
E         -  0,
E         +  9,
E           )
```

After:

```
E       AssertionError: assert (['ddsdsdads ', 'sfafsdsd', 'dfds sdfsef', 'sfdssdf ', 'sdsadfs', 'dsfsdfsd', 'cfdfdfd', 'dgffgfdgfd', 'fdsfsdgfsdgsf'], 1, 2, 3, 4, 5, 6, 7, 8, 9) == (['ddsdsdads ', 'sfafsdsd', 'dfds sdfsef', 'sfdssdf ', 'sdsadfs', 'dsfsdfsd', 'cfdfdfd', 'dgffgfdgfd', 'fdsfsdgfsdgsf'], 1, 2, 3, 4, 5, 6, 7, 8, 0)
E         At index 9 diff: 9 != 0
E         Full diff:
E           (
E            ['ddsdsdads ',
E             'sfafsdsd',
E             'dfds sdfsef',
E             'sfdssdf ',
E             'sdsadfs',
E             'dsfsdfsd',
E             'cfdfdfd',
E             'dgffgfdgfd',
E             'fdsfsdgfsdgsf'],
E            1,
E            2,
E            3,
E            4,
E            5,
E            6,
E            7,
E            8,
E         -  0,
E         +  9,
E           )
```

**Comment by alexmojaki** [comment]
This problem threw me off today, please can this be merged?

**Comment by samuelcolvin** [comment]
thanks so much.

**Pull request merged**
